services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    image: git.pku.edu.cn/uaaa/server:${TAG:-latest}
  
  server-full:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-full
    image: git.pku.edu.cn/uaaa/server-full:${TAG:-latest}

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
    image: git.pku.edu.cn/uaaa/ui:${TAG:-latest}

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    image: git.pku.edu.cn/uaaa/proxy:${TAG:-latest}
